### ISSUE TITLE
Pb installing via Docker

### ISSUE THREAD

**Issue by cmdcmdcmd** [openwhyd/openwhyd#78] opened 2017-07-24 08:34 UTC
Step 5/12 : COPY ./whydJS/node_modules/get /usr/src/app/node_modules/get
**ERROR: Service 'web' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder901008156/whydJS/node_modules/get: no such file or directory**

Any idea @nicolasleger ?

**Comment by adrienjoly** [comment] 2017-07-27 15:49
still not working, @cmdcmdcmd ?

If not, can you please:

1. delete your local `openwhyd` folder,
2. re-cloning a fresh copy of `openwhyd` and trying to make it run again, by following the same steps as [that demo](https://youtu.be/4IUMwCKkzik?t=20m10s) (you can skip the first 20 minutes of the video)
3. let us know at what step it's not working as expected

**Comment by nicolasleger** [comment] 2017-07-27 15:56
Have you removed the `node_modules` already present in the Git with some locals/custom modules?

**Comment by adrienjoly** [comment] 2017-07-27 15:58
@nicolasleger I have not, yet.

Do you think that these non-npm modules could be the cause of Claire's problem?

**Comment by nicolasleger** [comment] 2017-07-27 16:03
sorry I was asking @cmdcmdcmd 
the failing command is the one that copy that folder so I presumed

I had tricky problems when creating the Docker env with that `node_modules` folder since the `.dockerignore` and `dockercompose.yml` should exclude it except from those
and maybe it's a different Docker version managing that another way.

**Comment by adrienjoly** [comment] 2017-07-28 07:32
I guess that we could try to move these fake `node_modules` to a app/lib/` or something like that, if it has a chance to simplify the Docker configuration and possibly solve this problem. What do you think, @nicolasleger?

**Comment by nicolasleger** [comment] 2017-07-28 07:58
Yes If we can remove those folder it would be clearer.

**Comment by adrienjoly** [comment] 2017-07-28 08:08
=> just made this task: https://github.com/openwhyd/openwhyd/issues/80

Feel free to take it if you like. Otherwise, I'll try to do it in a few days.

**Comment by adrienjoly** [comment] 2017-08-13 09:02
Should be fixed by https://github.com/openwhyd/openwhyd/releases/tag/v1.0.3.
Closing.

**Closed by adrienjoly** 2017-08-13 09:02 UTC
Labels: bug, help wanted
