### ISSUE TITLE
Can't register a new user with facebook in production

### ISSUE THREAD

**Issue by SkinyMonkey** [openwhyd/openwhyd#120] opened 2017-11-20 22:35 UTC
It's not possible to register new users on openwhyd.org via facebook.

**Comment by adrienjoly** [comment] 2017-11-25 10:36
Maybe related to #47  ?

I will check that with a fake Facebook account, then try the PR:

- [ ] test fb signup, using `master` branch
- [ ] test fb signup, using SkinyMonkey's PR
- [ ] test regular signup, using SkinyMonkey's PR
- [ ] merge PR

**Comment by adrienjoly** [comment] 2017-11-25 10:44
Getting the following display when signing up with Facebook with current `master` branch:

![image](https://user-images.githubusercontent.com/531781/33229777-9cec4280-d1d5-11e7-956c-6586982c183c.png)

=> several things to fix:

- prevent the "Submit for Login Review" warning (caused by `whyd-dev would like to manage your Pages and publish as Pages you manage`, maybe ?)
- prevent the `You are using a display type of 'popup' in a large browser window or tab. For a better user experience, show this dialog with our JavaScript SDK without specifying an explicit display type. The SDK will choose the best display type for each environment.` warning (only visible to developers of the fb application)

**Comment by adrienjoly** [comment] 2017-11-25 10:52
FYI, after accepting Facebook auth, user still has to enter email and password:

![image](https://user-images.githubusercontent.com/531781/33229815-f88eac30-d1d6-11e7-8c85-24ae1aab8a99.png)

(on current version of `master` branch)

**Comment by adrienjoly** [comment] 2017-11-25 10:54
Removed permissions from fb account to whyd's fb app, then tested fb signup again.

Fb auth dialog looks much more reassuring now:

![image](https://user-images.githubusercontent.com/531781/33229833-54afd7be-d1d7-11e7-8c99-f6b26ede60a3.png)

**Comment by adrienjoly** [comment] 2017-11-25 11:02
[SkinyMonkey's PR](https://github.com/openwhyd/openwhyd/pull/123) works well => user does not have to enter email and password.

There is one drawback to this approach tho: many people provided a garbage/disposable email address when signing up to Facebook => not giving them an opportunity to update that email address means that they may never receive emails from Openwhyd (e.g. password retrieval procedure), unless they manually change their email address from their Openwhyd account settings.

**Comment by adrienjoly** [comment] 2017-11-25 11:11
@SkinyMonkey just merged your PR. Can you close this issue after checking that the problem is solved on your end?

**Closed** 2017-11-25 17:29 UTC
Labels: bug

**Comment by SkinyMonkey** [comment] 2017-11-25 17:30
@adrienjoly about the drawbacks : they wont receive openwhyd news, that's a good point, but they wont need to change their password .. they login through facebook :)
